language: csharp
sudo: false
env:
  - MONO_THREADS_PER_CPU=2000
os:
  - linux
  - osx
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - libunwind8
    - libicu-dev
before_install:
  - [ $TRAVIS_OS_NAME == "osx" ] || brew update
  - [ $TRAVIS_OS_NAME == "osx" ] || (brew list | grep icu4c || brew install icu4c)
script:
  - ./build.sh --quiet verify