using System.Collections.Generic;
using System.Linq;
using Microsoft.Framework.Runtime.Common.DependencyInjection;
using Xunit;

namespace Microsoft.Framework.Runtime.Tests
{
    public class ServiceProviderFacts
    {
        [Fact]
        public void RegisteredServicesCanBeIEnumerableResolved()
        {
            var serviceProvider = new ServiceProvider();
            var service = new Service();

            serviceProvider.Add(typeof(IService), service);

            var serviceList = (IEnumerable<IService>)serviceProvider.GetService(typeof(IEnumerable<IService>));

            Assert.NotNull(serviceList);
            var enumerator = serviceList.GetEnumerator();
            Assert.True(enumerator.MoveNext(), "The serviceList should have 1 element");
            Assert.Same(service, enumerator.Current);
            Assert.False(enumerator.MoveNext(), "The serviceList should have 1 element");
        }


        [Fact]
        public void NonRegisteredServicesCanBeIEnumerableResolved()
        {
            var serviceProvider = new ServiceProvider();

            var serviceList = (IEnumerable<IService>)serviceProvider.GetService(typeof(IEnumerable<IService>));

            Assert.NotNull(serviceList);
            Assert.False(serviceList.Any(), "The serviceList should have no elements.");
        }


        [Fact]
        public void VerifyManifestAutoGenerated()
        {
            var service = new Service();
            var fallbackProvider = new ServiceProvider();
            fallbackProvider.Add(typeof(IService), service);
            var serviceProvider = new ServiceProvider(fallbackProvider);
            serviceProvider.Add(typeof(Service), service);

            var manifest = serviceProvider.GetService(typeof(IServiceManifest)) as IServiceManifest;
            var fallbackManifest = fallbackProvider.GetService(typeof(IServiceManifest)) as IServiceManifest;

            Assert.NotNull(manifest);
            Assert.NotNull(fallbackManifest);

            Assert.NotNull(fallbackManifest.Services.Single(t => t == typeof(IService)));
            Assert.True(fallbackManifest.Services.Any(t => t == typeof(IService)));
            Assert.True(manifest.Services.Any(t => t == typeof(Service)));
        }

        private interface IService
        {
        }

        private class Service : IService
        {
        }
    }
}
