// <auto-generated />
namespace NuGet.Resolver
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Strings
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("NuGet.Resolver.Strings", typeof(Strings).GetTypeInfo().Assembly);

        /// <summary>
        /// Missing dependency information for package: {0}
        /// </summary>
        internal static string MissingDependencyInfo
        {
            get { return GetString("MissingDependencyInfo"); }
        }

        /// <summary>
        /// Missing dependency information for package: {0}
        /// </summary>
        internal static string FormatMissingDependencyInfo(object p0)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("MissingDependencyInfo"), p0);
        }

        /// <summary>
        /// Unable to satisfy package dependency constraints.
        /// </summary>
        internal static string NoSolution
        {
            get { return GetString("NoSolution"); }
        }

        /// <summary>
        /// Unable to satisfy package dependency constraints.
        /// </summary>
        internal static string FormatNoSolution()
        {
            return GetString("NoSolution");
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
